//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDF_CertificateAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSDF_CertCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSDF_CertCodes()
        {
            this.SSDF_Certificate = new HashSet<SSDF_Certificate>();
        }
    
        public string CertCode { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string LastEditBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSDF_Certificate> SSDF_Certificate { get; set; }
    }
}
